Description: >
  Patryk Pawlak | Udacity 2020
  AWS-CloudFormation script to create a IAM policy.

############################### Parameters ################################
Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String
    Default: UdagramApp

############################### Resources ################################
Resources:
  IAMRoleWebApp:
    Type: 'AWS::IAM::Role'
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'

  IAMWebAppS3IP:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
        - Ref: 'IAMRoleWebApp'

Outputs:
  IAMRoleWebApp:
    Description: 'Allow EC2 instances to manage Web App S3'
    Value: !Ref IAMWebAppS3IP
    Export:
      Name: !Sub ${EnvironmentName}-IAM-NAME
  IAMRoleWebAppArn:
    Description: Iam Instance Profile Arn
    Value: !GetAtt IAMRoleWebApp.Arn
    Export:
      Name: !Sub ${EnvironmentName}-IAM-ARN
